[package]
name = "freya-css"
version = "0.4.0-rc.18"
edition = "2024"
description = "CSS styling support for Freya."
license = "MIT"
authors = ["Marc Espín <mespinsanz@gmail.com>"]
readme = "../../README.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"
keywords = ["gui", "ui", "desktop", "css", "skia"]
categories = ["gui"]

# [lints]
# workspace = true

[dependencies]
# freya-core = { workspace = true }
# torin = { workspace = true }
freya-core = "0.4.0-rc.18"
torin = "0.4.0-rc.18"

[features]
mocked-engine = ["freya-core/mocked-engine"]

[dev-dependencies]
# freya = { workspace = true }
freya = "0.4.0-rc.18"
